### PR TITLE
Age Update madafaka.ejs

### PR DESCRIPTION
**Pull request by Belbol**

### CODE REVIEW

**Comment by djeada** [comment]
Perhaps the age could be calculated automatically, using a date module, for example.

**Comment by Belbol** [comment]
> Perhaps the age could be calculated automatically, using a date module, for example.

A perfect idea which i already thought about, which i also can't perform because i'm not really a programmer 😅

**Comment by djeada** [comment]
Don't undersell yourself, Belbol! I feel you are more than capable of completing the assignment.

**Comment by waelsy123** [comment]
I don't know how I missed this conversation LOL😃
indeed @Belbol since that you're learning Javascript, I will keep this task for you

**Review by waelsy123 — COMMENTED** [review]
could you please update the date to reflect my current age of 30?

**Pull request closed without merging**
